name: craft-ls
title: Craft Tools Language Server
summary: A Language Server Protocol implementation for *craft files.
description: |
  craft-ls enables editors that support the LSP to get quality of life improvements while working on *craft configuration files.
license: BSD-3-Clause
source-code:
  - https://github.com/Batalex/craft-ls
issues:
  - https://github.com/Batalex/craft-ls/issues/new

adopt-info: craft-ls
base: core24
confinement: strict
platforms:
  amd64:
  arm64:

parts:
  craft-ls:
    plugin: python
    source: .
    build-snaps:
      - astral-uv
    override-build: |
      uv export --format requirements-txt --no-dev -o requirements.txt
      craftctl set version="$(cat src/craft_ls/__init__.py | cut -d '"' -f2 | xargs)"
      craftctl default
    stage-packages:
      - python3-venv

apps:
  craft-ls:
    command: bin/craft-ls
    plugs:
      - home
