name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  # allow manual runs on branches without a PR

env:
  FORCE_COLOR: "1"

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v7.0.0
        with:
          python-version-file: ".python-version"

      - name: Install nox
        run: uv tool install nox

      - name: Run linter
        run: nox -s lint

  tests:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v7.0.0
        with:
          python-version-file: ".python-version"

      - name: Install nox
        run: uv tool install nox

      - name: Run tests
        run: nox -s tests

  validate_build:
    name: Build artifacts
    needs: [lint, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build snap
        uses: snapcore/action-build@v1

      - name: Execute snap
        run: |
          sudo snap install $(find . -type f -name '*.snap') --dangerous
          snap run craft-ls --version

      - uses: "DeterminateSystems/nix-installer-action@main"

      - name: Build Flake
        run: nix build

      - name: Execute flake
        run: ./result/bin/craft-ls --version
